### ISSUE TITLE
Create Element: Label

### ISSUE THREAD

**Issue by igorlourenco** [FotonTech/NFoTon#46]
Create an element Label and variants according to with the layouts in
https://www.figma.com/file/pSuBkbjhzZdq0nvHhDFbk7/crypter?node-id=457%3A249

![image](https://user-images.githubusercontent.com/43149318/122642674-03cec180-d0e2-11eb-8318-ed4b7a44106f.png)

**Comment by viniciushvc** [comment]
Assign this issue to me.

**Comment by joaopaulomoraes** [comment]
Are you working on it, @viniciushvc? I didn't pay attention and I already have 50%+ completed!

**Comment by viniciushvc** [comment]
@joaopaulomoraes no problem, you can take this issue

**Comment by igorlourenco** [comment]
Closing due #67.
Thanks @joaopaulomoraes and @viniciushvc for dedicating yourselves to this issue.
