### ISSUE TITLE
Create Element: Divider

### ISSUE THREAD

**Issue by igorlourenco** [FotonTech/NFoTon#47]
Create an element Divider and variants according to with the layouts in
https://www.figma.com/file/pSuBkbjhzZdq0nvHhDFbk7/crypter?node-id=457%3A257

![image](https://user-images.githubusercontent.com/43149318/122642914-39c07580-d0e3-11eb-8c55-ddcd8e705b2e.png)

**Comment by joaopaulomoraes** [comment]
I'm doing this one

**Comment by igorlourenco** [comment]
Closed due #66.
You are amazing @joaopaulomoraes.
