### ISSUE TITLE
Create Element: Burger Icon

### ISSUE THREAD

**Issue by allanneto** [FotonTech/NFoTon#50]
Create an element Burger Icon and variants according to the layouts in
https://www.figma.com/file/pSuBkbjhzZdq0nvHhDFbk7/crypter?node-id=457%3A254

- Use react-icons package FeatherIcons;; 
- Render the icon based on the variant prop (closed, open);
- Check if is possible to extend IconProps from react-icons.

![image](https://user-images.githubusercontent.com/54034635/122643469-6033e000-d0e6-11eb-9592-c27d9f482fc2.png)

**Comment by enriquebeta6** [comment]
Estou fazendo essa aqui
